{
  "formatVersion": "1.1",
  "component": {
    "group": "me.tamkungz",
    "module": "signals-bukkit",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "me.tamkungz",
          "module": "signals-core",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "signals-bukkit-0.1.0-SNAPSHOT.jar",
          "url": "signals-bukkit-0.1.0-SNAPSHOT.jar",
          "size": 11495,
          "sha512": "a9d8b68ccc369634678295239e34f3cee970539c0415d46f2b4f2f3559ea6b4dd6e1c4eb297404d633541044ad64c21ffea6ed522698d232dd0c3df6a96ca8e8",
          "sha256": "3eebd00c680dbcf978395a1cba2113720b314179507ca44c14ab038ceba6f330",
          "sha1": "d3d75e935cb615ead0e3bb0c569a3faacc26e358",
          "md5": "0d537ce4439b81ee745382dcbc7b8291"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "me.tamkungz",
          "module": "signals-core",
          "version": {
            "requires": "0.1.0-SNAPSHOT"
          }
        }
      ],
      "files": [
        {
          "name": "signals-bukkit-0.1.0-SNAPSHOT.jar",
          "url": "signals-bukkit-0.1.0-SNAPSHOT.jar",
          "size": 11495,
          "sha512": "a9d8b68ccc369634678295239e34f3cee970539c0415d46f2b4f2f3559ea6b4dd6e1c4eb297404d633541044ad64c21ffea6ed522698d232dd0c3df6a96ca8e8",
          "sha256": "3eebd00c680dbcf978395a1cba2113720b314179507ca44c14ab038ceba6f330",
          "sha1": "d3d75e935cb615ead0e3bb0c569a3faacc26e358",
          "md5": "0d537ce4439b81ee745382dcbc7b8291"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "signals-bukkit-0.1.0-SNAPSHOT-sources.jar",
          "url": "signals-bukkit-0.1.0-SNAPSHOT-sources.jar",
          "size": 7427,
          "sha512": "988dd932afad2103113a455d82459ff7fe3335d0fb52828436a8f2892a1697e04399ebd5fd67875a59de94a5f5a47ca54cf9e10233d78df3f2333c3500feddc3",
          "sha256": "e983696ad0b4c932e5814a57e2292d0edcbf0782f7e0cb7eed45a93db4f3d37e",
          "sha1": "ba7e3c2a344cdef29511017f9f5f5cbb50264326",
          "md5": "10a0a08d449ddb6c569e52a49649ae8c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "signals-bukkit-0.1.0-SNAPSHOT-javadoc.jar",
          "url": "signals-bukkit-0.1.0-SNAPSHOT-javadoc.jar",
          "size": 92581,
          "sha512": "45ae3067020643267e9ae90d86cc37a65dc7a5f34f413b0a04a7abf802930f201297645cad5a81d17ea2711eaa31224aaf580280facf3491442b7da2717206f7",
          "sha256": "fc7919dfbfa6aa787ccfa4c9e08919fef600c3ec8ada81533f314f509495a9ca",
          "sha1": "13f15dd85eecb3db73409eb9d2989b1f70ca91b7",
          "md5": "9c3e7e03bde5a7e5ebf3bad54e6c98a8"
        }
      ]
    },
    {
      "name": "shadowRuntimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "shadowed",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "signals-bukkit-0.1.0-SNAPSHOT-all.jar",
          "url": "signals-bukkit-0.1.0-SNAPSHOT-all.jar",
          "size": 34570,
          "sha512": "389f992ad690972cb98a10e56149fb9c7be1fd99ef42e5d87d45cdf6de2c9ed60b702551245f9baf9b2125b47dea505bdca910af2a9085bb8e55e3e15b652c45",
          "sha256": "9afb4436896afaaff38b3244ed15095931fbec44e8db699396da1e571fc4da66",
          "sha1": "10c81073498951d9ec785682af294375d2631099",
          "md5": "68d1cd272db830f15623d1ea744cf671"
        }
      ]
    }
  ]
}
