{
  "formatVersion": "1.1",
  "component": {
    "group": "me.tamkungz",
    "module": "signals-core",
    "version": "0.1.0-SNAPSHOT",
    "attributes": {
      "org.gradle.status": "integration"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14.2"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "foo.zaaarf.geb",
          "module": "core",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "signals-core-0.1.0-SNAPSHOT.jar",
          "url": "signals-core-0.1.0-SNAPSHOT.jar",
          "size": 19522,
          "sha512": "02e2136b78d8ae89d8aeb807945fb03a146a1efb2abaf661dee57db60426c33b7c2d2a4c0f3a54631ec86d57eefecea5721977dc7f46fadbad01f1ce6cc82c45",
          "sha256": "514d4d6e8acd92273d668100b37e043fd2494809247eedc8daa8879aa937db16",
          "sha1": "7d3092c542d6af5d99c5566dd9856353c1dc5a9e",
          "md5": "29eab4f7ddd9b34604b4a8726745acec"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "foo.zaaarf.geb",
          "module": "core",
          "version": {
            "requires": "0.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "signals-core-0.1.0-SNAPSHOT.jar",
          "url": "signals-core-0.1.0-SNAPSHOT.jar",
          "size": 19522,
          "sha512": "02e2136b78d8ae89d8aeb807945fb03a146a1efb2abaf661dee57db60426c33b7c2d2a4c0f3a54631ec86d57eefecea5721977dc7f46fadbad01f1ce6cc82c45",
          "sha256": "514d4d6e8acd92273d668100b37e043fd2494809247eedc8daa8879aa937db16",
          "sha1": "7d3092c542d6af5d99c5566dd9856353c1dc5a9e",
          "md5": "29eab4f7ddd9b34604b4a8726745acec"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "signals-core-0.1.0-SNAPSHOT-sources.jar",
          "url": "signals-core-0.1.0-SNAPSHOT-sources.jar",
          "size": 8500,
          "sha512": "6a8bc04efc288835dbad08cf0f56e0d406167c726f7d2dcafed79e8fe89052ad3af4ce613ba330cabf8af0cce7641d35c10007698313b911ca10808fdacdad10",
          "sha256": "22eb9136d4f9978c873b6b742b5b64604043f2cfb3bd37c4a45986815f48b730",
          "sha1": "f386a3bfd72d5d20ac61430b23dd1a58861f177a",
          "md5": "c086b43193ab8aa25ede17b1a07a3c2c"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "signals-core-0.1.0-SNAPSHOT-javadoc.jar",
          "url": "signals-core-0.1.0-SNAPSHOT-javadoc.jar",
          "size": 101060,
          "sha512": "3b65df2573384bdd5a15e3ad5c8a7ce6be93167c6e21f15a10bab1ff2d69c87230fe698ffca67a6a170fcb2d5fba0632746d26d05a8210197d54a7e72c59e681",
          "sha256": "44b8661bdffa47ed61a7fe98c4a7cb693ea8cc00e48acc2805ef9f8ec0f04ccc",
          "sha1": "eabac6be8dc7c7636fc983480d248c24d4c5d312",
          "md5": "efa3dd543067e8168f2cefa9423c424b"
        }
      ]
    }
  ]
}
